# Pertemuan 6 - Persiapan Data

**Nama:** Suryani Tangdiaga  
**NIM:** 250401020097  
**Kelas:** IF405

Materi:
- Handling Missing Values
- Encoding Kategorikal
- Train-Test Split
- Feature Scaling

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
df = sns.load_dataset('titanic')

cols = [
    'pclass',
    'sex',
    'age',
    'sibsp',
    'parch',
    'fare',
    'embarked',
    'survived'
]

df = df[cols].copy()

df.head()

   pclass     sex   age  sibsp  parch     fare embarked  survived
0       3    male  22.0      1      0   7.2500        S         0
1       1  female  38.0      1      0  71.2833        C         1
2       3  female  26.0      0      0   7.9250        S         1
3       1  female  35.0      1      0  53.1000        S         1
4       3    male  35.0      0      0   8.0500        S         0

In [3]:
print("Shape:")
print(df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nTipe Data:")
print(df.dtypes)

print("\nDistribusi Target:")
print(df['survived'].value_counts(normalize=True).round(3))

Shape:
(891, 8)

Missing Values:
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
survived      0
dtype: int64

Tipe Data:
pclass        int64
sex          object
age         float64
sibsp         int64
parch         int64
fare        float64
embarked     object
survived      int64
dtype: object

Distribusi Target:
survived
0    0.616
1    0.384
Name: proportion, dtype: float64

## Handling Missing Values

Kolom age diisi menggunakan median dan kolom embarked diisi menggunakan modus.

In [5]:
df['age'] = df['age'].fillna(df['age'].median())

df['embarked'] = df['embarked'].fillna(
    df['embarked'].mode()[0]
)

print(df.isnull().sum())

pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
survived    0
dtype: int64

## Encoding Data Kategorikal

Menggunakan One-Hot Encoding pada kolom sex dan embarked.

In [7]:
df = pd.get_dummies(
    df,
    columns=['sex','embarked'],
    drop_first=True,
    dtype=int
)

df.head()

,pclass,age,sibsp,parch,fare,survived,sex_male,embarked_Q,embarked_S
0,3,22.0,1,0,7.2500,0,1,0,1
1,1,38.0,1,0,71.2833,1,0,0,0
2,3,26.0,0,0,7.9250,1,0,0,1
3,1,35.0,1,0,53.1000,1,0,0,1
4,3,35.0,0,0,8.0500,0,1,0,1

In [8]:
print(df.columns.tolist())

['pclass', 'age', 'sibsp', 'parch', 'fare', 'survived', 'sex_male', 'embarked_Q', 'embarked_S']

In [9]:
print(df.columns.tolist())

['pclass', 'age', 'sibsp', 'parch', 'fare', 'survived', 'sex_male', 'embarked_Q', 'embarked_S']

## Train Test Split

Dataset dibagi menjadi data latih 80% dan data uji 20%.

In [11]:
X = df.drop('survived', axis=1)
y = df['survived']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train :", X_train.shape)
print("Test  :", X_test.shape)

Train : (712, 8)
Test  : (179, 8)

In [12]:
print("Train:")
print(y_train.value_counts(normalize=True).round(3))

print("\nTest:")
print(y_test.value_counts(normalize=True).round(3))

Train:
survived
0    0.617
1    0.383
Name: proportion, dtype: float64

Test:
survived
0    0.615
1    0.385
Name: proportion, dtype: float64

## Feature Scaling

Menggunakan StandardScaler hanya pada fitur numerik.

In [13]:
num_cols = [
    'pclass',
    'age',
    'sibsp',
    'parch',
    'fare'
]

scaler = StandardScaler()

X_train[num_cols] = scaler.fit_transform(
    X_train[num_cols]
)

X_test[num_cols] = scaler.transform(
    X_test[num_cols]
)

X_train.head()

,pclass,age,sibsp,parch,fare,sex_male,embarked_Q,embarked_S
692,0.829568,-0.112078,-0.465084,-0.466183,0.513812,1,0,1
481,-0.370945,-0.112078,-0.465084,-0.466183,-0.662563,1,0,1
527,-1.571457,-0.112078,-0.465084,-0.466183,3.955399,1,0,1
855,0.829568,-0.879807,-0.465084,0.727782,-0.467874,0,0,1
801,-0.370945,0.118241,0.478335,0.727782,-0.115977,0,0,1

In [14]:
print("Mean:")
print(scaler.mean_)

print("\nStd:")
print(scaler.scale_)

Mean:
[ 2.30898876 29.45985955  0.49297753  0.39044944 31.81982626]

Std:
[ 0.83297766 13.02541729  1.05997462  0.83754512 48.02534305]

# Kesimpulan

1. Dataset Titanic berhasil dipersiapkan untuk Machine Learning.
2. Missing values pada age dan embarked berhasil ditangani.
3. Variabel kategorikal berhasil dikonversi menggunakan One-Hot Encoding.
4. Dataset dibagi menjadi training set dan testing set menggunakan stratified split.
5. Fitur numerik berhasil dinormalisasi menggunakan StandardScaler sehingga siap digunakan untuk proses pemodelan Machine Learning.